/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import MainMedia.mediamethods;
import Holders.AudioHolder;
import Holders.InfoHolder;
import Util.MediaParser;
import Util.Print;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author sasuke
 */
public class AudioList extends javax.swing.JFrame {

    /**
     * Creates new form AudioList
     */
    
    
    ArrayList<InfoHolder> holder;
    String[] columns;
    
    public AudioList(final ArrayList<InfoHolder> holder){
    
        this.holder = holder;
        columns = new String[]{"","Title","Album","Artist",""};
        
        initComponents();
      
        jTable1.setRowHeight(50);
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.rowAtPoint(evt.getPoint());
                int col = jTable1.columnAtPoint(evt.getPoint());
                if (row >= 0 && col >= 0) {
                        Print.print(""+row);
                    try {
                       
                        int response = JOptionPane.showConfirmDialog(null, "Play with Inbuilt Player", "Confirm",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (response == JOptionPane.NO_OPTION) {
                              Desktop.getDesktop().open(new File(holder.get(row).Path));                     
                        } else if (response == JOptionPane.YES_OPTION) {
                                new mediamethods(new File(holder.get(row).Path)).setVisible(true);
                        } else if (response == JOptionPane.CLOSED_OPTION) {
                             Desktop.getDesktop().open(new File(holder.get(row).Path));                  
                        }                       
                       
                    } catch (IOException ex) {
                        Logger.getLogger(AudioList.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        
    }
    
 
    
    public AudioList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public TableCellRenderer getCellRenderer( int row, int column ) {
                return new PlusMinusCellRenderer();
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new AudioTableModel(holder,columns));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudioList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudioList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudioList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudioList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudioList().setVisible(true);
            }
        });
    }
    
    public class AudioTableModel extends AbstractTableModel {

    private ArrayList<InfoHolder> holder;
    private String columns[];
    
    public AudioTableModel(ArrayList<InfoHolder> holder,String columns[]) {
        this.holder=holder;
        this.columns=columns;
    }

    public int getColumnCount() {
        return columns.length;
    }

    public int getRowCount() {
        return holder.size();
    }

    public String getColumnName(int columnIndex) {      
        return columns[columnIndex];
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
        AudioHolder ah =(AudioHolder) holder.get(rowIndex);

        switch (columnIndex) {
        case 0: return MediaParser.IMAGE_OUTPUT_FOLDER+ah.Album+"-"+ah.Artist+".jpg";
        case 1: return ah.Title ;
        case 2: return ah.Album;
        case 3: return ah.Artist;
        case 4: return "";
        }
        
        return null;
    }

}
        
    
    class PlusMinusCellRenderer extends JPanel implements TableCellRenderer {
        public Component getTableCellRendererComponent(
                            final JTable table, Object value,
                            boolean isSelected, boolean hasFocus,
                            int row, int column) {
               
            
            switch (column) {
                case 4:
                    this.add( new JButton("Delete"));
                    break;
                case 0:
                    File file = new File(value.toString());
                    
                    if(file.exists()){
                    JLabel label = new JLabel();
                    StretchIcon icon = new StretchIcon(file.getPath());
                    label.setIcon(icon);
                    label.setPreferredSize(new Dimension(40,40));
                
                    this.add(label);
                    }
                  break;
                default:
                   
                    JLabel label;
                    if(value!=null)
                    label= new JLabel(value.toString());
                    else
                        label = new JLabel();
                     
                    this.add( label );
                    break;
            }
                
                return this;
        }
}
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
