/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Partials;

import Default.ProgressStage;
import Default.Scan;
import Default.SplashScreen;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author sasuke
 */


public class ScanningProgress extends javax.swing.JPanel {

    /**
     * Creates new form ScanningProgress
     */
    private ArrayList<String> paths;
    private Scan scan;
    private ProgressStage stage;
    private DefaultListModel model;
    
    public ScanningProgress(ArrayList<String> paths) {
        initComponents();     
        this.paths = paths;
        model = new DefaultListModel();
        progressList.setModel(model);
        jButton1.setEnabled(false);
        
        stage = new ProgressStage() {
            @Override
            public void progressStarted() {
                String message = "Getting all the media Paths";
                progressMessage.setText(message);
                model.addElement(message);
                jProgressBar1.setIndeterminate(true);
            }

            @Override
            public void progressFounds(int total) {
                progressMessage.setText("Extracting Values from files");
                model.addElement("Total files found :"+total);              
                jProgressBar1.setIndeterminate(false);
                jProgressBar1.setMaximum(total);
            }

            @Override
            public void progressCurrent(int progress, String message) {
                jProgressBar1.setValue(progress);
                model.addElement(message);
            }

            @Override
            public void progressCompleted() {
                progressMessage.setText("Scanning completed");
                model.addElement("Scanning completed");
                jButton1.setEnabled(true);
            }
        };
        
        scan= new Scan(stage);
        scan.initiateScan(this.paths);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        progressMessage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        progressList = new javax.swing.JList<>();

        progressMessage.setFont(new java.awt.Font("Titillium Web", 0, 14)); // NOI18N
        progressMessage.setText("Progress Message here");

        jButton1.setFont(new java.awt.Font("Titillium Web", 0, 14)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(progressList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(progressMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(progressMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SplashScreen screen = new SplashScreen();
        screen.setVisible(true);
          
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> progressList;
    private javax.swing.JLabel progressMessage;
    // End of variables declaration//GEN-END:variables
}
