import Default.ProgressStage;
import Default.Scan;
import Default.ExtractMetadata;
import Database.MediaBase;
import Util.MediaParser;
import Util.Print;
import Holders.InfoHolder;
import Holders.VideoHolder;
import Holders.AudioHolder;
import Holders.ImageHolder;
import UI.AudioTab;
import UI.ImagesTabbed;
import Util.QueryBuilder;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.tika.metadata.Metadata;
import org.apache.tika.parser.Parser;
import org.apache.tika.parser.jpeg.JpegParser;
import org.apache.tika.parser.mp3.Mp3Parser;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author sasuke
 */
public class SplashScreen extends javax.swing.JFrame {
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int returnVal = fc.showOpenDialog(SplashScreen.this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            ProgressStage stage = new ProgressStage(){
                @Override
                public void progressStarted() {
                }

                @Override
                public void progressCurrent(int progress) {
                System.out.println(progress);                   
                }

                @Override
                public void progressCompleted(ArrayList<String> images,ArrayList<String> audios,ArrayList<String> videos) {
                  
                        if(audios.size()>0){ 
                            Mp3Parser parser = new Mp3Parser();
                            insertToDatabase(audios,parser,MediaParser.TYPE_AUDIO);
                        }
                        
                        if(images.size()>0){
                            JpegParser imageParser = new JpegParser();
                            insertToDatabase(images,imageParser,MediaParser.TYPE_IMAGE);
                        }
                    
                }
            };
            
            Scan scan = new Scan(stage);
            scan.initiateScan(file);
            
        } else {
                JOptionPane.showMessageDialog(rootPane," Wasnt approved");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void insertToDatabase(ArrayList<String> files,Parser parser,int type){
       ExtractMetadata extractMetadata = new ExtractMetadata(parser);
       MediaBase mediaBase = new MediaBase();       
       
       for(String file : files){        
           try{
               Print.print(file);
            File path = new File(file);
            Metadata data =extractMetadata.extractData(path);
            Print.print("------------------------------------------------------------------------------------------");
           
            InfoHolder holder = MediaParser.parse(data, path, type);
            mediaBase.insert(holder);
       }
        catch(Exception e){
            Print.print("Error :"+e.getMessage());
        }
       }
       
        try {
            mediaBase.close();
        } catch (SQLException ex) {
            Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void printMedia(InfoHolder infoHolder){
    
        Print.print(infoHolder.Id+"");
        Print.print(infoHolder.File_Name);
        Print.print(infoHolder.Folder_Name);
        Print.print(infoHolder.Path);
        Print.print(infoHolder.Created_At+"");
        Print.print(infoHolder.Recently_Viewed+"");
        Print.print(infoHolder.Size+"");
      
        if(infoHolder instanceof AudioHolder){      
            AudioHolder holder = (AudioHolder) infoHolder; 
            Print.print(holder.Title);
            Print.print(holder.Album);
            Print.print(holder.Artist);
            Print.print(holder.Genre);
            Print.print(holder.Song_Year+"");
            Print.print(holder.Length+"");
        }
        else if(infoHolder instanceof ImageHolder){      
          ImageHolder holder = (ImageHolder) infoHolder;
            Print.print(holder.Width+"");
            Print.print(holder.Height+"");
        }else if(infoHolder instanceof VideoHolder){
        
        }       
    }
    
    private void print(Metadata metadata){
    
     String[] metadataNames = metadata.names();
      for(String name : metadataNames) {		        
    	  System.out.println(name + ": " + metadata.get(name));
      }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        /*
File[] paths;
// returns pathnames for files and directory
paths = File.listRoots();

// for each pathname in pathname array
for(File path:paths)
{
    // prints file and directory paths
    System.out.println("Drive Name: "+path);
}
*/
        
    ArrayList<InfoHolder> holder = null;

        try {
            MediaBase base = new MediaBase();
             String sql = "Select * from Audios,Main where Audios.Main_Id=Main.ID";    
             String[] basicCol={QueryBuilder.COL_ID,
                 QueryBuilder.COL_FILE_NAME,
                 QueryBuilder.COL_FOLDER_NAME,
                 QueryBuilder.COL_PATH};
             
             String[] specificCol={
             QueryBuilder.COL_TITLE,
             QueryBuilder.COL_ALBUM,
             QueryBuilder.COL_ARTIST,
             QueryBuilder.COL_GENRE,
             QueryBuilder.COL_SONG_YEAR,
             QueryBuilder.COL_LENGTH};
             
            holder = base.getValues(sql,MediaParser.TYPE_AUDIO,basicCol,specificCol);           
            base.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(holder!=null){     
        int max = holder.size();
        for(int i=0;i<max;i++){
            
            Print.print("-----------------------------------------------------------");
            printMedia(holder.get(i));
            
            }
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        ArrayList<InfoHolder> holder = null;

        try {
            MediaBase base = new MediaBase();
            String sql = "Select * from Images,Main where Images.Main_Id=Main.ID";                
            String[] basicCol={QueryBuilder.COL_ID,
                 QueryBuilder.COL_FILE_NAME,
                 QueryBuilder.COL_FOLDER_NAME,
                 QueryBuilder.COL_CREATED_AT,
                 QueryBuilder.COL_RECENTLY_VIEWED,
                 QueryBuilder.COL_PATH};
             
             String[] specificCol={
                 QueryBuilder.COL_HEIGHT,
                 QueryBuilder.COL_WIDTH};
             
            holder = base.getValues(sql,MediaParser.TYPE_IMAGE,basicCol,specificCol);           
            base.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        new ImagesTabbed(holder).setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       new AudioTab().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
